site_name: "SIGE IE"

theme:
  name: lux
  favicon: assets/favicon.ico
  logo: assets/favicon.ico
  font:
    text: Roboto
  language: pt
  features:
    - content.code.annotate
    - content.tabs.link
    - header.autohide
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - navigation.tabs.sticky
  extra_css:
    - theme/bootstrap.min.css
    - css/custom.css

nav:
  - Landing Pages: landingPages/<!DOCTYPE html>.html
  - Ínicio: index.md
  - Subir o projeto:
      - Backend: info/backend.md
      - Frontend: info/frontend.md
      - Contribuições: info/contribuir.md
  - Atas de Reunião:
      - Ata 1: atas/ata1.md
      - Ata 2: atas/ata2.md
      - Ata 3: atas/ata3.md
  - Arquitetura e Protótipo:
      - Arquitetura: info/arquitetura.md
      - Modelagem Banco de dados: info/modelagemBD.md
  - RoadMap:
      - RoadMap: info/Roadmap.md
  - Cronograma:
      - Cronograma: info/cronograma.md
      - Releases: 
          - Release 1: releases/Release1.md
          - Release 2: releases/release2.md
          - Release 3: releases/release3.md
          - Release 4: releases/release4.md
  - Requisitos de  Software:
      - Épicos: info/requisitosEpicos.md
      - Features: info/requisitosFeatures.md

plugins:
  - search