# Generated by Django 4.2 on 2024-04-18 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('places', '0019_delete_atmosfericdischargesystem'),
        ('systems', '0006_remove_equipment_equipmentphoto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systems.system')),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(null=True, upload_to='equipment_photos/')),
                ('description', models.CharField(max_length=50)),
                ('equipmentType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipments.equipmenttype')),
            ],
        ),
        migrations.CreateModel(
            name='AtmosphericDischargeSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atmospheric_discharge_systems', to='places.place')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atmospheric_discharge_systems', to='places.room')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atmospheric_discharge_systems', to='systems.system')),
            ],
            options={
                'db_table': 'atmospheric_discharge_systems',
            },
        ),
    ]
