# Generated by Django 4.2 on 2024-04-24 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0004_rename_equipment_equipmentdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atmosphericdischargeequipment',
            name='room',
        ),
    ]
