# Generated by Django 4.2 on 2024-04-24 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0022_area_delete_room'),
        ('equipments', '0005_remove_atmosphericdischargeequipment_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='atmosphericdischargeequipment',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='places.area'),
        ),
    ]
