# Generated by Django 4.2 on 2024-04-24 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0006_atmosphericdischargeequipment_area'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='atmosphericdischargeequipment',
            table='atmospheric_discharge_equipments',
        ),
        migrations.AlterModelTable(
            name='equipmentdetail',
            table='equipment_details',
        ),
        migrations.AlterModelTable(
            name='equipmenttype',
            table='equipment_types',
        ),
    ]
