# Generated by Django 4.2 on 2024-04-25 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0009_rename_equipment_atmosphericdischargeequipment_equipment_detail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipmenttype',
            old_name='type',
            new_name='name',
        ),
    ]
