# Generated by Django 4.2 on 2024-04-25 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0023_alter_area_place'),
        ('equipments', '0011_rename_placeowner_equipmentdetail_place_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='SructeredCablingEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='places.area')),
                ('equipment_detail', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='equipments.equipmentdetail')),
            ],
        ),
        migrations.CreateModel(
            name='IluminationEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='places.area')),
                ('equipment_detail', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='equipments.equipmentdetail')),
            ],
        ),
        migrations.CreateModel(
            name='FireAlarmEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='places.area')),
                ('equipment_detail', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='equipments.equipmentdetail')),
            ],
        ),
        migrations.CreateModel(
            name='ElectricalLoadEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='places.area')),
                ('equipment_detail', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='equipments.equipmentdetail')),
            ],
        ),
        migrations.CreateModel(
            name='ElectricalLineEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='places.area')),
                ('equipment_detail', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='equipments.equipmentdetail')),
            ],
        ),
        migrations.CreateModel(
            name='ElectricalCircuitEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='places.area')),
                ('equipment_detail', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='equipments.equipmentdetail')),
            ],
        ),
        migrations.CreateModel(
            name='DistributionBoardEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='places.area')),
                ('equipment_detail', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='equipments.equipmentdetail')),
            ],
        ),
    ]
