# Generated by Django 4.2 on 2024-05-03 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0008_delete_atmosphericdischargesystem'),
        ('equipments', '0013_atmosphericdischargeequipment_system_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atmosphericdischargeequipment',
            name='system',
            field=models.OneToOneField(default=7, on_delete=django.db.models.deletion.CASCADE, to='systems.system'),
        ),
        migrations.AlterField(
            model_name='distributionboardequipment',
            name='system',
            field=models.OneToOneField(default=5, on_delete=django.db.models.deletion.CASCADE, to='systems.system'),
        ),
        migrations.AlterField(
            model_name='electricalcircuitequipment',
            name='system',
            field=models.OneToOneField(default=4, on_delete=django.db.models.deletion.CASCADE, to='systems.system'),
        ),
        migrations.AlterField(
            model_name='electricallineequipment',
            name='system',
            field=models.OneToOneField(default=3, on_delete=django.db.models.deletion.CASCADE, to='systems.system'),
        ),
        migrations.AlterField(
            model_name='electricalloadequipment',
            name='system',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, to='systems.system'),
        ),
        migrations.AlterField(
            model_name='firealarmequipment',
            name='system',
            field=models.OneToOneField(default=8, on_delete=django.db.models.deletion.CASCADE, to='systems.system'),
        ),
        migrations.AlterField(
            model_name='iluminationequipment',
            name='system',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='systems.system'),
        ),
        migrations.AlterField(
            model_name='sructeredcablingequipment',
            name='system',
            field=models.OneToOneField(default=6, on_delete=django.db.models.deletion.CASCADE, to='systems.system'),
        ),
    ]
