# Generated by Django 4.2 on 2024-05-03 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0008_delete_atmosphericdischargesystem'),
        ('places', '0026_alter_area_place'),
        ('equipments', '0014_alter_atmosphericdischargeequipment_system_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SructeredCablingEquipment',
            new_name='StructuredCablingEquipment',
        ),
        migrations.AlterModelTable(
            name='distributionboardequipment',
            table='equipments_distribution_board_equipments',
        ),
        migrations.AlterModelTable(
            name='electricalcircuitequipment',
            table='equipments_electrical_circuit_equipments',
        ),
        migrations.AlterModelTable(
            name='electricallineequipment',
            table='equipments_electrical_line_equipments',
        ),
        migrations.AlterModelTable(
            name='electricalloadequipment',
            table='equipments_electrical_load_equipments',
        ),
        migrations.AlterModelTable(
            name='firealarmequipment',
            table='equipments_fire_alarm_equipments',
        ),
        migrations.AlterModelTable(
            name='iluminationequipment',
            table='equipments_ilumination_equipments',
        ),
        migrations.AlterModelTable(
            name='structuredcablingequipment',
            table='equipments_structured_cabling_equipments',
        ),
    ]
