# Generated by Django 4.2 on 2024-05-23 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0008_delete_atmosphericdischargesystem'),
        ('places', '0028_place_photo'),
        ('equipments', '0018_personalequipmenttype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmentdetail',
            name='description',
        ),
        migrations.RemoveField(
            model_name='equipmentdetail',
            name='photo',
        ),
        migrations.CreateModel(
            name='RefrigerationEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='places.area')),
                ('equipment_detail', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='equipments.equipmentdetail')),
                ('system', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='systems.system')),
            ],
            options={
                'db_table': 'refrigeration_equipments',
            },
        ),
        migrations.CreateModel(
            name='EquipmentPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(null=True, upload_to='equipment_photos/')),
                ('description', models.CharField(max_length=50)),
                ('equipment_detail', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='equipments.equipmentdetail')),
            ],
        ),
    ]
