# Generated by Django 4.2 on 2024-06-05 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0019_remove_equipmentdetail_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmentphoto',
            name='equipment_detail',
        ),
        migrations.AddField(
            model_name='equipmentphoto',
            name='equipmentType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='equipments.equipmenttype'),
        ),
        migrations.AddField(
            model_name='equipmentphoto',
            name='personalEquipmentType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='equipments.personalequipmenttype'),
        ),
        migrations.AlterField(
            model_name='equipmentphoto',
            name='description',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
