# Generated by Django 4.2 on 2024-06-12 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0021_remove_equipmentphoto_equipmenttype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentphoto',
            name='equipment_detail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='equipments.equipmentdetail'),
        ),
    ]
