# Generated by Django 4.2 on 2024-06-14 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_placeowner_user'),
        ('systems', '0008_delete_atmosphericdischargesystem'),
        ('equipments', '0022_equipmentphoto_equipment_detail'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EquipmentDetail',
            new_name='Equipment',
        ),
        migrations.RenameModel(
            old_name='EquipmentType',
            new_name='GenericEquipmentCategory',
        ),
        migrations.RenameModel(
            old_name='PersonalEquipmentType',
            new_name='PersonalEquipmentCategory',
        ),
        migrations.RenameField(
            model_name='atmosphericdischargeequipment',
            old_name='equipment_detail',
            new_name='equipment',
        ),
        migrations.RenameField(
            model_name='distributionboardequipment',
            old_name='equipment_detail',
            new_name='equipment',
        ),
        migrations.RenameField(
            model_name='electricalcircuitequipment',
            old_name='equipment_detail',
            new_name='equipment',
        ),
        migrations.RenameField(
            model_name='electricallineequipment',
            old_name='equipment_detail',
            new_name='equipment',
        ),
        migrations.RenameField(
            model_name='electricalloadequipment',
            old_name='equipment_detail',
            new_name='equipment',
        ),
        migrations.RenameField(
            model_name='equipment',
            old_name='equipmentType',
            new_name='genericEquipmentCategory',
        ),
        migrations.RenameField(
            model_name='equipment',
            old_name='personalEquipmentType',
            new_name='personalEquipmentCategory',
        ),
        migrations.RenameField(
            model_name='equipmentphoto',
            old_name='equipment_detail',
            new_name='equipment',
        ),
        migrations.RenameField(
            model_name='firealarmequipment',
            old_name='equipment_detail',
            new_name='equipment',
        ),
        migrations.RenameField(
            model_name='iluminationequipment',
            old_name='equipment_detail',
            new_name='equipment',
        ),
        migrations.RenameField(
            model_name='refrigerationequipment',
            old_name='equipment_detail',
            new_name='equipment',
        ),
        migrations.RenameField(
            model_name='structuredcablingequipment',
            old_name='equipment_detail',
            new_name='equipment',
        ),
        migrations.AlterModelTable(
            name='genericequipmentcategory',
            table='equipments_generic_equipment_categories',
        ),
        migrations.AlterModelTable(
            name='personalequipmentcategory',
            table='equipments_personal_equipment_categories',
        ),
    ]
