# Generated by Django 4.2 on 2024-06-14 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0023_rename_equipmentdetail_equipment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='genericEquipmentCategory',
            new_name='generic_equipment_category',
        ),
        migrations.RenameField(
            model_name='equipment',
            old_name='personalEquipmentCategory',
            new_name='personal_equipment_category',
        ),
    ]
