<<<<<<< HEAD
# Generated by Django 4.2 on 2024-06-18 20:55
=======
# Generated by Django 4.2 on 2024-06-19 17:19
>>>>>>> e260bab191b745a2f6aeae909f64ebf246e6ef1f

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0031_remove_place_access_code'),
        ('equipments', '0027_alter_atmosphericdischargeequipment_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atmosphericdischargeequipment',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='atmospheric_discharge_equipment', to='places.area'),
        ),
        migrations.AlterField(
            model_name='distributionboardequipment',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='distribution_board_equipment', to='places.area'),
        ),
        migrations.AlterField(
            model_name='electricalcircuitequipment',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='electrical_circuit_equipment', to='places.area'),
        ),
        migrations.AlterField(
            model_name='electricallineequipment',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='electrical_line_equipment', to='places.area'),
        ),
        migrations.AlterField(
            model_name='electricalloadequipment',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='electrical_load_equipment', to='places.area'),
        ),
        migrations.AlterField(
            model_name='firealarmequipment',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fire_alarm_equipment', to='places.area'),
        ),
        migrations.AlterField(
            model_name='iluminationequipment',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ilumination_equipment', to='places.area'),
        ),
        migrations.AlterField(
            model_name='refrigerationequipment',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refrigeration_equipment', to='places.area'),
        ),
        migrations.AlterField(
            model_name='structuredcablingequipment',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='structured_cabling_equipment', to='places.area'),
        ),
    ]
