# Generated by Django 4.2 on 2024-06-21 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_placeowner_user'),
        ('systems', '0008_delete_atmosphericdischargesystem'),
        ('equipments', '0028_alter_atmosphericdischargeequipment_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='place_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='users.placeowner'),
        ),
        migrations.AlterField(
            model_name='firealarmequipment',
            name='equipment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fire_alarm', to='equipments.equipment'),
        ),
        migrations.AlterField(
            model_name='refrigerationequipment',
            name='system',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, to='systems.system'),
        ),
        migrations.AlterModelTable(
            name='refrigerationequipment',
            table='equipments_refrigeration_equipments',
        ),
    ]
