# Generated by Django 4.2 on 2024-06-30 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0030_alter_equipment_place_owner'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='atmosphericdischargeequipment',
            table='atmospheric_discharges',
        ),
        migrations.AlterModelTable(
            name='distributionboardequipment',
            table='distribution_boards',
        ),
        migrations.AlterModelTable(
            name='electricalcircuitequipment',
            table='electrical_circuits',
        ),
        migrations.AlterModelTable(
            name='electricallineequipment',
            table='electrical_lines',
        ),
        migrations.AlterModelTable(
            name='electricalloadequipment',
            table='electrical_loads',
        ),
        migrations.AlterModelTable(
            name='equipment',
            table='equipments',
        ),
        migrations.AlterModelTable(
            name='equipmentphoto',
            table='equipment_photos',
        ),
        migrations.AlterModelTable(
            name='firealarmequipment',
            table='fire_alarms',
        ),
        migrations.AlterModelTable(
            name='genericequipmentcategory',
            table='generic_equipment_categories',
        ),
        migrations.AlterModelTable(
            name='iluminationequipment',
            table='illuminations',
        ),
        migrations.AlterModelTable(
            name='personalequipmentcategory',
            table='personal_equipment_categories',
        ),
        migrations.AlterModelTable(
            name='refrigerationequipment',
            table='refrigeration_equipments',
        ),
        migrations.AlterModelTable(
            name='structuredcablingequipment',
            table='structured_cabling',
        ),
    ]
