# Generated by Django 4.2 on 2024-06-30 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0031_alter_atmosphericdischargeequipment_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='atmosphericdischargeequipment',
            table='equipments_atmospheric_discharges',
        ),
        migrations.AlterModelTable(
            name='distributionboardequipment',
            table='equipments_distribution_boards',
        ),
        migrations.AlterModelTable(
            name='electricalcircuitequipment',
            table='equipments_electrical_circuits',
        ),
        migrations.AlterModelTable(
            name='electricallineequipment',
            table='equipments_electrical_lines',
        ),
        migrations.AlterModelTable(
            name='electricalloadequipment',
            table='equipments_electrical_loads',
        ),
        migrations.AlterModelTable(
            name='equipmentphoto',
            table='equipments_photos',
        ),
        migrations.AlterModelTable(
            name='firealarmequipment',
            table='equipments_fire_alarms',
        ),
        migrations.AlterModelTable(
            name='iluminationequipment',
            table='equipments_illuminations',
        ),
        migrations.AlterModelTable(
            name='refrigerationequipment',
            table='equipments_refrigeration',
        ),
        migrations.AlterModelTable(
            name='structuredcablingequipment',
            table='equipments_structured_cabling',
        ),
    ]
