# Generated by Django 4.2 on 2024-07-09 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0032_alter_atmosphericdischargeequipment_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributionboardequipment',
            name='dps',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='distributionboardequipment',
            name='dr',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='distributionboardequipment',
            name='grounding',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='distributionboardequipment',
            name='method_installation',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='distributionboardequipment',
            name='power',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='distributionboardequipment',
            name='type_material',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='electricalcircuitequipment',
            name='isolament',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='electricalcircuitequipment',
            name='size',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='electricalloadequipment',
            name='brand',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='electricalloadequipment',
            name='model',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='electricalloadequipment',
            name='power',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='electricalloadequipment',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='iluminationequipment',
            name='format',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='iluminationequipment',
            name='power',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='iluminationequipment',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='iluminationequipment',
            name='tecnology',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='refrigerationequipment',
            name='power',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='refrigerationequipment',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
