# Generated by Django 4.2 on 2024-07-17 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0033_distributionboardequipment_dps_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atmosphericdischargeequipment',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='distributionboardequipment',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='electricalcircuitequipment',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='electricallineequipment',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='firealarmequipment',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='structuredcablingequipment',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
