# Generated by Django 4.2 on 2024-07-10 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0033_distributionboardequipment_dps_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='place_owner',
        ),
    ]
