# Generated by Django 4.2 on 2024-07-10 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0034_remove_equipment_place_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iluminationequipment',
            name='tecnology',
        ),
    ]
