# Generated by Django 4.2 on 2024-08-07 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0035_alter_equipmentphoto_equipment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electricalcircuitequipment',
            name='isolament',
        ),
        migrations.RemoveField(
            model_name='electricalcircuitequipment',
            name='quantity',
        ),
    ]
