# Generated by Django 4.2 on 2024-07-10 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0035_remove_iluminationequipment_tecnology'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iluminationequipment',
            name='format',
        ),
        migrations.RemoveField(
            model_name='iluminationequipment',
            name='power',
        ),
        migrations.RemoveField(
            model_name='iluminationequipment',
            name='quantity',
        ),
    ]
