# Generated by Django 4.2 on 2024-08-08 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0036_remove_electricalcircuitequipment_isolament_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='atmosphericdischargeequipment',
            name='observation',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='distributionboardequipment',
            name='observation',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='electricalcircuitequipment',
            name='observation',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='electricalcircuitequipment',
            name='type_circuit_breaker',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='electricalcircuitequipment',
            name='type_wire',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='electricallineequipment',
            name='observation',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='electricalloadequipment',
            name='observation',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='equipmentphoto',
            name='observation',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='firealarmequipment',
            name='observation',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='iluminationequipment',
            name='observation',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='refrigerationequipment',
            name='observation',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='structuredcablingequipment',
            name='observation',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
