# Generated by Django 4.2 on 2024-08-08 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0037_atmosphericdischargeequipment_observation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmentphoto',
            name='observation',
        ),
    ]
