# Generated by Django 4.2 on 2024-08-13 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0038_remove_equipmentphoto_observation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributionboardequipment',
            name='method_installation',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
