# Generated by Django 4.2 on 2024-08-16 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0038_remove_equipmentphoto_observation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electricalcircuitequipment',
            name='type_circuit_breaker',
        ),
    ]
