# Generated by Django 4.2 on 2024-04-23 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('places', '0021_room_place_room_systems'),
        ('equipments', '0002_equipment_placeowner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtmosphericDischarge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atmospheric_discharges', to='equipments.equipment')),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='atmospheric_discharges', to='places.place')),
            ],
            options={
                'db_table': 'atmospheric_discharges',
            },
        ),
    ]
