# Generated by Django 4.2 on 2024-04-23 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atmosphericdischarges', '0002_alter_atmosphericdischarge_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atmosphericdischarge',
            name='equipment',
        ),
    ]
