# Generated by Django 4.2 on 2024-04-18 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0004_equipmentphoto_equipmenttype_equipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='equipmentPhoto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='systems.equipmentphoto'),
        ),
    ]
