# Generated by Django 4.2 on 2024-04-19 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0007_atmosphericdischargesystem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AtmosphericDischargeSystem',
        ),
    ]
