# Generated by Django 4.2 on 2024-04-10 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('places', '0007_remove_place_user_place_place_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='place_owner',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.placeowner'),
        ),
    ]
