# Generated by Django 4.2 on 2024-04-10 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_alter_place_place_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='place',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='places.place'),
        ),
    ]
