# Generated by Django 4.2 on 2024-04-10 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('places', '0009_alter_room_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='place_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.placeowner'),
        ),
        migrations.AlterField(
            model_name='room',
            name='place',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='rooms', to='places.place'),
        ),
    ]
