# Generated by Django 4.2 on 2024-04-12 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0014_alter_room_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='places.place'),
        ),
    ]
