# Generated by Django 4.2 on 2024-04-17 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0001_initial'),
        ('places', '0017_atmosfericdischargesystem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atmosfericdischargesystem',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atmosferic_discharge_systems', to='places.place'),
        ),
        migrations.AlterField(
            model_name='atmosfericdischargesystem',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atmosferic_discharge_systems', to='places.room'),
        ),
        migrations.AlterField(
            model_name='atmosfericdischargesystem',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atmosferic_discharge_systems', to='systems.system'),
        ),
        migrations.AlterModelTable(
            name='atmosfericdischargesystem',
            table='atmosferic_discharge_system',
        ),
    ]
