# Generated by Django 4.2 on 2024-04-17 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0018_alter_atmosfericdischargesystem_place_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AtmosfericDischargeSystem',
        ),
    ]
