# Generated by Django 4.2 on 2024-04-18 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0019_delete_atmosfericdischargesystem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='place',
        ),
        migrations.RemoveField(
            model_name='room',
            name='systems',
        ),
    ]
