# Generated by Django 4.2 on 2024-04-24 19:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systems', '0008_delete_atmosphericdischargesystem'),
        ('equipments', '0005_remove_atmosphericdischargeequipment_room'),
        ('places', '0021_room_place_room_systems'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('floor', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='places.place')),
                ('systems', models.ManyToManyField(to='systems.system')),
            ],
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
