# Generated by Django 4.2 on 2024-04-24 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0022_area_delete_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='places.place'),
        ),
    ]
