# Generated by Django 4.2 on 2024-04-25 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0023_alter_area_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='lon',
            field=models.FloatField(null=True),
        ),
    ]
