# Generated by Django 4.2 on 2024-05-03 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0024_place_lat_place_lon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='systems',
        ),
    ]
