# Generated by Django 4.2 on 2024-05-03 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0025_remove_area_systems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='places.place'),
        ),
    ]
