# Generated by Django 4.2 on 2024-06-12 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_placeeditor'),
        ('places', '0028_place_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='editors',
            field=models.ManyToManyField(related_name='places', to='users.placeeditor'),
        ),
    ]
