# Generated by Django 4.2 on 2024-06-12 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0029_place_editors'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='access_code',
            field=models.CharField(blank=True, max_length=36, null=True, unique=True),
        ),
    ]
