# Generated by Django 4.2 on 2024-06-12 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0030_place_access_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='access_code',
        ),
    ]
